### ISSUE TITLE
[2.0-dev] Uncaught Joomla\Database\Exception\PrepareStatementFailureException: Unknown column

### ISSUE THREAD

**Issue by csthomas** [joomla-framework/database#117]
### Steps to reproduce the issue
Create a query with column value like `SELECT 'hello';`

```php

print_r($db->setQuery($db->getQuery(true)->select('ala'))->loadColumn());
PHP Warning:  Uncaught Joomla\Database\Exception\PrepareStatementFailureException: Unknown column 'ala' in 'field list' in /home/tomash/public_html/database/src/Mysqli/MysqliStatement.php:124
Stack trace:
#0 /home/tomash/public_html/database/src/Mysqli/MysqliDriver.php(860): Joomla\Database\Mysqli\MysqliStatement->__construct(Object(mysqli), 'SELECT ala')
#1 /home/tomash/public_html/database/src/DatabaseDriver.php(1755): Joomla\Database\Mysqli\MysqliDriver->prepareStatement('SELECT ala')
#2 php shell code(1): Joomla\Database\DatabaseDriver->setQuery(Object(Joomla\Database\Mysqli\MysqliQuery))
#3 {main}
  thrown in /home/tomash/public_html/database/src/Mysqli/MysqliStatement.php on line 124
```

### Expected result
Should work.

### System information (as much as possible)
2.0-dev

### Additional comments
I tested it by `php -a` and use `require '../vendor/autoload.php';`

**Comment by csthomas** [comment]
Mistake
